# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0056aae1a59443d4f52a305f1241fcb7058279f525ab0e8c2a7093b0811589440fcbe1fb55451f7435a1af9a210f73ef9508bc74e6c77e57ec63f8da9e5646e

test:
  secret_key_base: cdf57dc2ca91faa81a8e1281dabf417c844dc2ce7bc96ecdeb7c19501647d4a917d39ae1ccc00213b5fa0c7d98da61eb907af0cf137c0c60e043de6dc46b7d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
